package cn.feihutv.zhibofeihu.data.db.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 3): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        HistoryRecordBeanDao.createTable(db, ifNotExists);
        MessageEntityDao.createTable(db, ifNotExists);
        MvDownLogDao.createTable(db, ifNotExists);
        NoticeSnsEntityDao.createTable(db, ifNotExists);
        NoticeSysEntityDao.createTable(db, ifNotExists);
        RecentItemDao.createTable(db, ifNotExists);
        SearchHistoryInfoDao.createTable(db, ifNotExists);
        SysConfigBeanDao.createTable(db, ifNotExists);
        SysFontColorBeanDao.createTable(db, ifNotExists);
        SysGameBetBeanDao.createTable(db, ifNotExists);
        SysGiftNewBeanDao.createTable(db, ifNotExists);
        SysGoodsNewBeanDao.createTable(db, ifNotExists);
        SysGuardGoodsBeanDao.createTable(db, ifNotExists);
        SysHBBeanDao.createTable(db, ifNotExists);
        SysItemBeanDao.createTable(db, ifNotExists);
        SysLaunchTagBeanDao.createTable(db, ifNotExists);
        SysLevelBeanDao.createTable(db, ifNotExists);
        SysMountNewBeanDao.createTable(db, ifNotExists);
        SysSignAwardBeanDao.createTable(db, ifNotExists);
        SysTipsBeanDao.createTable(db, ifNotExists);
        SysVipBeanDao.createTable(db, ifNotExists);
        SysVipGoodsBeanDao.createTable(db, ifNotExists);
        TCRoomInfoDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        HistoryRecordBeanDao.dropTable(db, ifExists);
        MessageEntityDao.dropTable(db, ifExists);
        MvDownLogDao.dropTable(db, ifExists);
        NoticeSnsEntityDao.dropTable(db, ifExists);
        NoticeSysEntityDao.dropTable(db, ifExists);
        RecentItemDao.dropTable(db, ifExists);
        SearchHistoryInfoDao.dropTable(db, ifExists);
        SysConfigBeanDao.dropTable(db, ifExists);
        SysFontColorBeanDao.dropTable(db, ifExists);
        SysGameBetBeanDao.dropTable(db, ifExists);
        SysGiftNewBeanDao.dropTable(db, ifExists);
        SysGoodsNewBeanDao.dropTable(db, ifExists);
        SysGuardGoodsBeanDao.dropTable(db, ifExists);
        SysHBBeanDao.dropTable(db, ifExists);
        SysItemBeanDao.dropTable(db, ifExists);
        SysLaunchTagBeanDao.dropTable(db, ifExists);
        SysLevelBeanDao.dropTable(db, ifExists);
        SysMountNewBeanDao.dropTable(db, ifExists);
        SysSignAwardBeanDao.dropTable(db, ifExists);
        SysTipsBeanDao.dropTable(db, ifExists);
        SysVipBeanDao.dropTable(db, ifExists);
        SysVipGoodsBeanDao.dropTable(db, ifExists);
        TCRoomInfoDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(HistoryRecordBeanDao.class);
        registerDaoClass(MessageEntityDao.class);
        registerDaoClass(MvDownLogDao.class);
        registerDaoClass(NoticeSnsEntityDao.class);
        registerDaoClass(NoticeSysEntityDao.class);
        registerDaoClass(RecentItemDao.class);
        registerDaoClass(SearchHistoryInfoDao.class);
        registerDaoClass(SysConfigBeanDao.class);
        registerDaoClass(SysFontColorBeanDao.class);
        registerDaoClass(SysGameBetBeanDao.class);
        registerDaoClass(SysGiftNewBeanDao.class);
        registerDaoClass(SysGoodsNewBeanDao.class);
        registerDaoClass(SysGuardGoodsBeanDao.class);
        registerDaoClass(SysHBBeanDao.class);
        registerDaoClass(SysItemBeanDao.class);
        registerDaoClass(SysLaunchTagBeanDao.class);
        registerDaoClass(SysLevelBeanDao.class);
        registerDaoClass(SysMountNewBeanDao.class);
        registerDaoClass(SysSignAwardBeanDao.class);
        registerDaoClass(SysTipsBeanDao.class);
        registerDaoClass(SysVipBeanDao.class);
        registerDaoClass(SysVipGoodsBeanDao.class);
        registerDaoClass(TCRoomInfoDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
