package cn.feihutv.zhibofeihu.data.db.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_HISTORY_INFO".
*/
public class SearchHistoryInfoDao extends AbstractDao<SearchHistoryInfo, String> {

    public static final String TABLENAME = "SEARCH_HISTORY_INFO";

    /**
     * Properties of entity SearchHistoryInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Content = new Property(0, String.class, "content", true, "CONTENT");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
    }


    public SearchHistoryInfoDao(DaoConfig config) {
        super(config);
    }
    
    public SearchHistoryInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_HISTORY_INFO\" (" + //
                "\"CONTENT\" TEXT PRIMARY KEY NOT NULL ," + // 0: content
                "\"TIME\" INTEGER NOT NULL );"); // 1: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_HISTORY_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchHistoryInfo entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
        stmt.bindLong(2, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchHistoryInfo entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
        stmt.bindLong(2, entity.getTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SearchHistoryInfo readEntity(Cursor cursor, int offset) {
        SearchHistoryInfo entity = new SearchHistoryInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // content
            cursor.getLong(offset + 1) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchHistoryInfo entity, int offset) {
        entity.setContent(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SearchHistoryInfo entity, long rowId) {
        return entity.getContent();
    }
    
    @Override
    public String getKey(SearchHistoryInfo entity) {
        if(entity != null) {
            return entity.getContent();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchHistoryInfo entity) {
        return entity.getContent() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
