package cn.feihutv.zhibofeihu.data.db.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SYS_LEVEL_BEAN".
*/
public class SysLevelBeanDao extends AbstractDao<SysLevelBean, String> {

    public static final String TABLENAME = "SYS_LEVEL_BEAN";

    /**
     * Properties of entity SysLevelBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Level = new Property(0, String.class, "level", true, "LEVEL");
        public final static Property NeedExp = new Property(1, String.class, "needExp", false, "NEED_EXP");
    }


    public SysLevelBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SysLevelBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SYS_LEVEL_BEAN\" (" + //
                "\"LEVEL\" TEXT PRIMARY KEY NOT NULL ," + // 0: level
                "\"NEED_EXP\" TEXT);"); // 1: needExp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SYS_LEVEL_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SysLevelBean entity) {
        stmt.clearBindings();
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(1, level);
        }
 
        String needExp = entity.getNeedExp();
        if (needExp != null) {
            stmt.bindString(2, needExp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SysLevelBean entity) {
        stmt.clearBindings();
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(1, level);
        }
 
        String needExp = entity.getNeedExp();
        if (needExp != null) {
            stmt.bindString(2, needExp);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SysLevelBean readEntity(Cursor cursor, int offset) {
        SysLevelBean entity = new SysLevelBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // level
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // needExp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SysLevelBean entity, int offset) {
        entity.setLevel(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNeedExp(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SysLevelBean entity, long rowId) {
        return entity.getLevel();
    }
    
    @Override
    public String getKey(SysLevelBean entity) {
        if(entity != null) {
            return entity.getLevel();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SysLevelBean entity) {
        return entity.getLevel() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
