package cn.feihutv.zhibofeihu.data.db.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SYS_TIPS_BEAN".
*/
public class SysTipsBeanDao extends AbstractDao<SysTipsBean, String> {

    public static final String TABLENAME = "SYS_TIPS_BEAN";

    /**
     * Properties of entity SysTipsBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Tid = new Property(0, String.class, "tid", true, "TID");
        public final static Property Cond = new Property(1, String.class, "cond", false, "COND");
        public final static Property Text = new Property(2, String.class, "text", false, "TEXT");
    }


    public SysTipsBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SysTipsBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SYS_TIPS_BEAN\" (" + //
                "\"TID\" TEXT PRIMARY KEY NOT NULL ," + // 0: tid
                "\"COND\" TEXT," + // 1: cond
                "\"TEXT\" TEXT);"); // 2: text
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SYS_TIPS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SysTipsBean entity) {
        stmt.clearBindings();
 
        String tid = entity.getTid();
        if (tid != null) {
            stmt.bindString(1, tid);
        }
 
        String cond = entity.getCond();
        if (cond != null) {
            stmt.bindString(2, cond);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SysTipsBean entity) {
        stmt.clearBindings();
 
        String tid = entity.getTid();
        if (tid != null) {
            stmt.bindString(1, tid);
        }
 
        String cond = entity.getCond();
        if (cond != null) {
            stmt.bindString(2, cond);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SysTipsBean readEntity(Cursor cursor, int offset) {
        SysTipsBean entity = new SysTipsBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // tid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cond
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // text
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SysTipsBean entity, int offset) {
        entity.setTid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCond(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SysTipsBean entity, long rowId) {
        return entity.getTid();
    }
    
    @Override
    public String getKey(SysTipsBean entity) {
        if(entity != null) {
            return entity.getTid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SysTipsBean entity) {
        return entity.getTid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
